const {StyleSheet} = require('react-native');

const myStyle = StyleSheet.create({
  mainView: {
    flex: 1,
    backgroundColor: 'rgb(15,139,166)',
  },
  brandTxt: {
    color: 'white',
    textAlign: 'center',
    fontSize: 30,
    fontWeight: 'bold',
    fontFamily: 'aerial',
    margin: 0,
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: {width: -1, height: 1},
    textShadowRadius: 10,
    marginTop: 40,
  },
  inputView: {
    flex: 1,
    alignItems: 'center',
    marginTop: 30,
  },
  inputStyle: {
    backgroundColor: 'white',
    color: 'black',
    width: 300,
    marginTop: 20,
    padding: 7,
    borderRadius: 5,
    paddingLeft: 20,
    color: 'black',
    fontSize: 15,
  },
  pressBtn: {
    backgroundColor: 'rgb(223,80,19)',
    width: 200,
    height: 40,
    textAlign: 'center',
    padding: 5,
    borderRadius: 10,
    shadowOffset: {width: -2, height: 4},
    shadowColor: 'grey',
    shadowOpacity: 0.1,
    shadowRadius: 3,
    marginTop: 40,
  },
  btnTxt: {
    color: 'white',
    fontSize: 20,
    textAlign: 'center',
    fontFamily: 'BricolageGrotesque_18pt-SemiBold',
  },
  accountStyle: {
    flex: 1,
    alignItems: 'center',
    marginTop:200
  },
  joinHead: {
    fontSize: 22,
    fontFamily: 'BricolageGrotesque_18pt-SemiBold',
    color: 'white',
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: {width: -1, height: 1},
    textShadowRadius: 10,
  },
  pressBtnAcc: {
    borderColor: 'orangered',
    borderWidth: 3,
    width: 200,
    height: 45,
    textAlign: 'center',
    padding: 3,
    borderRadius: 10,
    shadowOffset: {width: -2, height: 4},
    shadowColor: 'white',
    shadowOpacity: 0.5,
    shadowRadius: 3,
    marginTop: 40,
  },
  imgJoin: {
    width: 350,
    height: 350,
    objectFit: 'contain',
    marginLeft: 50,
  },
});

export default myStyle;
